add_executable(${AE_CURRENT_EXECUTABLE_NAME} ${AE_CURRENT_SOURCE_FILES})
add_dependencies(${AE_CURRENT_EXECUTABLE_NAME} ${AE_LIBRARY_NAME})
target_link_libraries(${AE_CURRENT_EXECUTABLE_NAME} ${AE_LIBRARIES})

if(APPLE)
	set_target_properties(${AE_CURRENT_EXECUTABLE_NAME} PROPERTIES
		MACOSX_BUNDLE ON
		XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "${AE_CODESIGN_IDENTITY}"
		OUTPUT_NAME ${AE_CURRENT_BUNDLE_NAME})

	set(CMAKE_INSTALL_PREFIX ${CMAKE_CURRENT_BINARY_DIR})
	if("${CMAKE_GENERATOR}" STREQUAL "Xcode")
		# CMAKE_CURRENT_BINARY_DIR does not include CONFIG path with Xcode builds
		set(CMAKE_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}/${CMAKE_BUILD_TYPE})
	endif()
	install(CODE "
		include(BundleUtilities)
		set(BU_CHMOD_BUNDLE_ITEMS TRUE)
		fixup_bundle(\"${CMAKE_INSTALL_PREFIX}/${AE_CURRENT_BUNDLE_NAME}.app\" \"\" \"${AE_DEPS_LIBRARY_DIRS}\")
	" COMPONENT Runtime)
endif()
