name: MacOS
on: [push]
jobs:
  build-and-test:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v4
      - name: Create Build Directory
        run: cmake -E make_directory build_ci
      - name: Configure
        run: cmake -S . -B build_ci -DCMAKE_BUILD_TYPE=Release -DAE_LEAN_AND_MEAN=OFF
      - name: Build
        run: make -C build_ci all -j$(nproc)
      - name: Test
        run: build_ci/test/test
