name: Ubuntu MinGW
on: [push]
jobs:
  build-and-test:
      runs-on: ubuntu-latest
      container:
        image: ${{ vars.AE_BUILD_IMAGE || 'ghcr.io/johnhues/aether-build:latest' }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      steps:
      - uses: actions/checkout@v4
      - name: Create Build Directory
        run: cmake -E make_directory build_ci
      - name: Configure
        run: cmake -S . -B build_ci -DCMAKE_TOOLCHAIN_FILE=.github/toolchains/mingw-w64.cmake -DCMAKE_BUILD_TYPE=Release -DAE_LEAN_AND_MEAN=OFF
      - name: Build
        run: make -C build_ci all -j$(nproc)
      - name: Test
        env:
          WINEPREFIX: /tmp/wineprefix
        run: wine build_ci/test/test.exe
