name: Windows
on: [push]
jobs:
  build-and-test:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v4
      - name: Create Build Directory
        run: cmake -E make_directory build
      - name: Configure
        run: cmake -S . -B build -DAE_LEAN_AND_MEAN=OFF
      - name: Build
        run: cmake --build build --config Release
      - name: Test
        run: build\test\Release\test.exe
