name: Windows
on: [push]
jobs:
  build-and-test:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v4
      - name: Create Build Directory
        run: cmake -E make_directory build_ci
      - name: Configure
        run: cmake -S . -B build_ci -DAE_LEAN_AND_MEAN=OFF
      - name: Build
        run: cmake --build build_ci --config Release
      - name: Test
        run: build_ci\test\Release\test.exe
